- hosts: localhost
  become: true
  tasks:
    - name: Make alacritty discoverable
      ansible.builtin.command: cp target/release/alacritty /usr/local/bin
      args:
        chdir: /home/root/alacritty
    - name: Svg's
      ansible.builtin.command: cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
      args:
        chdir: /home/root/alacritty
    - name: Desktop Install
      ansible.builtin.command: desktop-file-install extra/linux/Alacritty.desktop
      args:
        chdir: /home/root/alacritty
    - name: Update Desktop Database
      ansible.builtin.command: update-desktop-database
      args:
        chdir: /home/root/alacritty
