- hosts: localhost
  become: true
  pre_tasks: 
  - name: Update cache
    apt: 
      update_cache: true
    tags: 
      - git
      - vim
      - curl
      - zsh
  tasks: 
  - name: Install git  
    apt: name=git
    tags:
      - git
  - name: Install vim  
    apt: name=vim
    tags:
      - vim
  - name: Install curl  
    apt: name=curl
    tags:
      - curl
  - name: Install zsh  
    shell: chsh -s $(which zsh)
    tags:
      - zsh
  - name: Install omz
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    tags:
      - zsh
  - name: Install zsh autosuggestions
    ansible.builtin.git:
      repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
      dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
    tags:
      - zsh
